### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by kognise** [eddiejibson/dubium#1]
Could we get some benchmarks against other popular dateformatting libraries? Here are some possible candidates:

- [Moment.js](https://momentjs.com/)
- [date-format](https://www.npmjs.com/package/date-format)
- [dateformat](https://www.npmjs.com/package/dateformat)
- [date-fns](https://date-fns.org/)

**Comment by eddiejibson** [comment]
Hello,

Thanks for your suggestion. I'll try implementing it soon.

**Comment by eddiejibson** [comment]
Implemented it here: https://github.com/eddiejibson/dubium#benchmarks.

Will add more soon.

Thanks again.

Closed #1.
