### ISSUE TITLE
IE11 syntax error

### ISSUE THREAD

**Issue by grofzero** [eddiejibson/dubium#4]
Hi,

The main property in the package json should point to the built version of the lib in the dist folder(dist/dubium.min.js), so I could import it directly.

Thank you

**Comment by eddiejibson** [comment]
Hi, the main in the package.json is for NodeJS use. As said, if you'd like to use it for a browser application just import in the built version. They're slightly different. Normally if you're bundling your NPM packages for browser use anyway it should still work?

**Comment by grofzero** [comment]
Hi, 

I just a took a look around and maybe you should use this field for the client side: https://docs.npmjs.com/files/package.json#browser

**Comment by eddiejibson** [comment]
Do you know if this is only for use of the client-side? I'm wondering why you need this though as normally if you import a npm package for a browser application on build (bundle) of such it'll still work? I don't know if the browser field will automatically mean it'll bundle properly with whatever you're using it for? Perhaps with whatever builder you're using to convert to suitable browser JavaScript you can set the option as to what browsers you want it to support? Are you using webpack/babel?

I'm currently on vacation but I'll try and implement when I get back, thanks for the suggestion 😀

**Comment by grofzero** [comment]
We're using webpack with babel, but when I import your module like: import dubium from 'dubium'; it will import the file, that the main property points to, and because we unfortunately must support IE11 it fails, so I have to use import dubium from 'dubium/dist/dubium.min.js', but that's not so pretty:) I'm not sure but as I understand, the main property will be used in node environment and browser for the browser.

**Comment by eddiejibson** [comment]
Alright, I'll give it a go. However, if you want to bundle well for other browsers you can use that base code from the main in package.json and use "targets" with Babel for it to work (see our webpack.config.js as that's what  we use for bundling, too)

**Comment by eddiejibson** [comment]
Assuming end of discussion, closing. Feel free to re-open.

**Comment by eddiejibson** [comment]
Hi @grofzero ,

I just implemented the suggestions provided by you in version 0.0.13. Let me know if it helps.

Thanks again.

**Comment by eddiejibson** [comment]
Closed.
